version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

services:
  toposoid-common-nlp-english-web:
    image: toposoid-common-nlp-english-web:0.4-SNAPSHOT
    tty: true
    environment:
      - SYNONYM_NOUN_SIMILARITY_THRESHHOLD_EN=0.52
      - SYNONYM_VERB_SIMILARITY_THRESHHOLD_EN=0.52
      - WORD2VEC_SIMILARITY_THRESHHOLD_EN=0.78
      - TOPOSOID_SENTENCEBERT_MODEL_EN=sentence-transformers/paraphrase-multilingual-mpnet-base-v2
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    ports:
      - 9008:9008
