version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

services:
  toposoid-common-nlp-english-web:
    image: toposoid/toposoid-common-nlp-english-web:0.5-SNAPSHOT
    environment:
      - TOPOSOID_SYNONYM_NOUN_SIMILARITY_THRESHHOLD_EN=0.52
      - TOPOSOID_SYNONYM_VERB_SIMILARITY_THRESHHOLD_EN=0.52
      - TOPOSOID_WORD2VEC_SIMILARITY_THRESHHOLD_EN=0.78
      - TOPOSOID_SENTENCEBERT_MODEL_EN=sentence-transformers/paraphrase-multilingual-mpnet-base-v2
      - TOPOSOID_SPACY_MODEL_EN=en_core_web_lg
      - SENTENCE_TRANSFORMERS_HOME=./models
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    ports:
      - 9008:9008



