version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

services:
  scala-common-nlp-english-web:
    image: toposoid/scala-common-nlp-english-web:0.1-SNAPSHOT
    environment:
      - SYNONYM_NOUN_SIMILARITY_THRESHHOLD=0.52
      - SYNONYM_VERB_SIMILARITY_THRESHHOLD=0.52
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    ports:
      - 9008:9008



